In [1]:
import pandas as pd
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
from shapely.geometry import Point, Polygon
import shapefile as shp

%matplotlib inline

In [2]:
def read_shapefile(sf):
    """
    Read a shapefile into a Pandas dataframe with a 'coords' 
    column holding the geometry information. This uses the pyshp
    package
    """
    fields = [x[0] for x in sf.fields][1:]
    records = sf.records()
    shps = [s.points for s in sf.shapes()]
    df = pd.DataFrame(columns=fields, data=records)
    df = df.assign(coords=shps)
    return df

def plot_map(sf, x_lim = None, y_lim = None, figsize = (11,9)):
    '''
    Plot map with lim coordinates
    '''
    plt.figure(figsize = figsize)
    id=0
    for shape in sf.shapeRecords():
        x = [i[0] for i in shape.shape.points[:]]
        y = [i[1] for i in shape.shape.points[:]]
        plt.plot(x, y, 'k')
        
        if (x_lim == None) & (y_lim == None):
            x0 = np.mean(x)
            y0 = np.mean(y)
            plt.text(x0, y0, id, fontsize=10)
        id = id+1
    
    if (x_lim != None) & (y_lim != None):     
        plt.xlim(x_lim)
        plt.ylim(y_lim)

In [3]:
tran_path = "austria-latest-free.shp/gis_osm_transport_free_1.shp"

In [4]:
sf = gpd.read_file(tran_path, encoding='utf-8')
sf['latitude'] = sf.geometry.y
sf['longitude'] = sf.geometry.x
sf = sf.astype({"osm_id": int})
sf.head()

,osm_id,code,fclass,name,geometry,latitude,longitude
0,380143,5621,bus_stop,Wolf in der Au,POINT (16.23715 48.20475),48.204745,16.237151
1,380266,5621,bus_stop,Purkersdorf Zentrum Bahnhof,POINT (16.17681 48.20568),48.205678,16.176812
2,380340,5621,bus_stop,Neupurkersdorf Richter-Minder-Siedlung,POINT (16.13456 48.19367),48.193666,16.134558
3,380562,5621,bus_stop,Dürrwien Autobahnanschluss,POINT (16.05953 48.17732),48.177324,16.059532
4,381141,5621,bus_stop,Preyergasse/Speising,POINT (16.28511 48.17388),48.173884,16.285108

In [5]:
# filter on railway stations
sf_rw = sf[sf.fclass == 'railway_station']
# exlude NA values
sf_rw = sf_rw[sf_rw.name.notna()]

In [6]:
u1_osm_id_list = [
    67029576,
    4140677491,
    4155298891,
    4155452193,
    4155868489,
    4160807391,
    4161088301,
    4169259989,
    4169472889,
    4169757308,
    3309570450,
    4174037289,
    4560869524,
    3500528328,
    3503264091,
    3500582336,
    1839787470,
    4167184427,
    4167184437,
    2018072723,
    2018072720,
    2018072719,
    2018072721,
    2018072722
]

u2_osm_id_list = [
    3598308198,
    3598290667,
    3598290671,
    4076415290,
    4076631293,
    4076716391,
    4077783491,
    4078094389,
    4073135889,
    4073027290,
    4073146389,
    3862884256,
    3309570450,
    4086541541,
    4560843528,
    4347738147,
    4104690590,
    4560869523,
    4123615290,
    3503264091
]

u3_osm_id_list = [
    8091317,
    4161779364,
    4161779363,
    4161774320,
    4161769952,
    4281897753,
    4348437231,
    4348437215,
    4560869523,
    4348336039,
    3500528328,
    4348336040,
    4003949409,
    69468988,
    115184107,
    60215284,
    4348320098,
    62687115,
    62687123,
    69484904,
    117527786
]

u4_osm_id_list = [
    3488454904,
    3488513522,
    4003901212,
    4003901213,
    4560843528,
    4560869524,
    4003949409,
    3993298632,
    3503264091,
    3993342689,
    3993342690,
    3993274359,
    1352828685,
    3993274361,
    3993274358,
    3993274357,
    3993274362,
    3993274360,
    321330275
]

u6_osm_id_list = [
    4005736525,
    4281927209,
    3324474915,
    4281939061,
    4281932864,
    3488513522,
    4283722992,
    4283722994,
    4283722991,
    4283722989,
    4283722990,
    4283722993,
    4281904637,
    4281897753,
    4281875074,
    3993274359,
    4012141489,
    3071028227,
    4008355785,
    4008355780,
    4008355779,
    4008355781,
    4008355782,
    4005731390
]

In [7]:
sf_rw_u1 = sf_rw[sf_rw['osm_id'].isin(u1_osm_id_list)]
sf_rw_u2 = sf_rw[sf_rw['osm_id'].isin(u2_osm_id_list)]
sf_rw_u3 = sf_rw[sf_rw['osm_id'].isin(u3_osm_id_list)]
sf_rw_u4 = sf_rw[sf_rw['osm_id'].isin(u4_osm_id_list)]
sf_rw_u6 = sf_rw[sf_rw['osm_id'].isin(u6_osm_id_list)]

In [8]:
sf_rw_u1.head()

,osm_id,code,fclass,name,geometry,latitude,longitude
497,67029576,5601,railway_station,Leopoldau,POINT (16.45207 48.27758),48.277582,16.452070
15141,1839787470,5601,railway_station,Wien Hauptbahnhof,POINT (16.37785 48.18501),48.185010,16.377855
16528,2018072719,5601,railway_station,Alaudagasse,POINT (16.38236 48.15369),48.153695,16.382355
16529,2018072720,5601,railway_station,Altes Landgut,POINT (16.38322 48.16229),48.162293,16.383225
16530,2018072721,5601,railway_station,Neulaa,POINT (16.38561 48.14577),48.145766,16.385606

In [93]:
class Station:
    def __init__(self, osm_id, name, latitude, longitude):
        # direction is not needed since it is user-centric map
        self.osm_id = osm_id
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
        self.neighbour_stations = []
        self.lines = []
        self.next_station = None
        
    def add_neighbour_station(self, station):
        self.neighbour_stations.append(station)
        
    def add_line(self, line):
        self.lines.append(line)
        
    def __str__(self):
        s = "station name: " + str(self.name)
        s += "\tneighbour_stations:"
        s += "\t"
        for st in self.neighbour_stations:
            s += st.name + ', '
        return s

In [96]:
ubahn = []
# u1_osm_ids = list(sf_rw_u1.osm_id)
u1_osm_ids = u1_osm_id_list

for i in u1_osm_ids:
    row = sf_rw_u1[sf_rw_u1.osm_id == i]
    s = Station(row.osm_id.values[0], str(row.name.values[0]), row.latitude.values[0], row.longitude.values[0])
    ubahn.append(s)

In [97]:
for i in range(0, len(ubahn)):
    s = ubahn[i]
    if i > 0:
        s.add_neighbour_station(ubahn[i-1])
    if i < len(ubahn)-1:
        s.add_neighbour_station(ubahn[i+1])

In [98]:
for s in ubahn:
    print(s)

station name: Leopoldau	neighbour_stations:	Großfeldsiedlung,
station name: Großfeldsiedlung	neighbour_stations:	Leopoldau, Aderklaaer Straße,
station name: Aderklaaer Straße	neighbour_stations:	Großfeldsiedlung, Rennbahnweg,
station name: Rennbahnweg	neighbour_stations:	Aderklaaer Straße, Kagraner Platz,
station name: Kagraner Platz	neighbour_stations:	Rennbahnweg, Kagran,
station name: Kagran	neighbour_stations:	Kagraner Platz, Alte Donau,
station name: Alte Donau	neighbour_stations:	Kagran, Kaisermühlen VIC,
station name: Kaisermühlen VIC	neighbour_stations:	Alte Donau, Donauinsel,
station name: Donauinsel	neighbour_stations:	Kaisermühlen VIC, Vorgartenstraße,
station name: Vorgartenstraße	neighbour_stations:	Donauinsel, Wien Praterstern,
station name: Wien Praterstern	neighbour_stations:	Vorgartenstraße, Nestroyplatz,
station name: Nestroyplatz	neighbour_stations:	Wien Praterstern, Schwedenplatz,
station name: Schwedenplatz	neighbour_stations:	Nestroyplatz, Stephansplatz,
station name: Stephansplatz	neighbour_stations:	Schwedenplatz, Karlsplatz,
station name: Karlsplatz	neighbour_stations:	Stephansplatz, Taubstummengasse,
station name: Taubstummengasse	neighbour_stations:	Karlsplatz, Wien Hauptbahnhof,
station name: Wien Hauptbahnhof	neighbour_stations:	Taubstummengasse, Keplerplatz,
station name: Keplerplatz	neighbour_stations:	Wien Hauptbahnhof, Reumannplatz,
station name: Reumannplatz	neighbour_stations:	Keplerplatz, Troststraße,
station name: Troststraße	neighbour_stations:	Reumannplatz, Altes Landgut,
station name: Altes Landgut	neighbour_stations:	Troststraße, Alaudagasse,
station name: Alaudagasse	neighbour_stations:	Altes Landgut, Neulaa,
station name: Neulaa	neighbour_stations:	Alaudagasse, Oberlaa,
station name: Oberlaa	neighbour_stations:	Neulaa,

In [99]:
ubahn

[<__main__.Station at 0x7ff3f155f910>,
 <__main__.Station at 0x7ff3f155f790>,
 <__main__.Station at 0x7ff3f167ddc0>,
 <__main__.Station at 0x7ff3f167dca0>,
 <__main__.Station at 0x7ff430580e50>,
 <__main__.Station at 0x7ff3eeff90a0>,
 <__main__.Station at 0x7ff3f15e4580>,
 <__main__.Station at 0x7ff430585c10>,
 <__main__.Station at 0x7ff3f156d730>,
 <__main__.Station at 0x7ff430593e20>,
 <__main__.Station at 0x7ff43058a3d0>,
 <__main__.Station at 0x7ff3f155f610>,
 <__main__.Station at 0x7ff3f155f310>,
 <__main__.Station at 0x7ff3f155fd00>,
 <__main__.Station at 0x7ff3f155f850>,
 <__main__.Station at 0x7ff3f155f4f0>,
 <__main__.Station at 0x7ff3f155fb20>,
 <__main__.Station at 0x7ff3f155fe50>,
 <__main__.Station at 0x7ff3f155f670>,
 <__main__.Station at 0x7ff3f155fc70>,
 <__main__.Station at 0x7ff3f155ffa0>,
 <__main__.Station at 0x7ff3f155f2b0>,
 <__main__.Station at 0x7ff3f155f040>,
 <__main__.Station at 0x7ff3f155f2e0>]